// apps/projects/src/app/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {
  constructor(private router: Router) {}
  isMenuOpen: boolean = false;
  links: { path: string; name: string; external: boolean }[] = [
    {
      path: '/',
      name: 'About',
      external: true,
    },
    {
      path: '/',
      name: 'Projects',
      external: false,
    },
    {
      path: '/contact',
      name: 'Contact',
      external: true,
    },

    {
      path: '/admin',
      name: 'Admin',
      external: true,
    },
  ];
  closeModal() {
    this.isMenuOpen = false;
  }

  setIsOpen() {
    this.isMenuOpen = !this.isMenuOpen;
  }
  href(event:any) {
    event.preventDefault()
    this.isMenuOpen = false
    setTimeout(() => {
      window.location.href =  event.target.href
    }, 600);
  }
}

<nav class="navbar--desktop">
  <!-- Credits https://codepen.io/yuhomyan/pen/ExKvNVa -->
  <input (click)="setIsOpen()" type="checkbox" [checked]="isMenuOpen" id="active" />
  <label for="active" class="menu-btn"><span></span></label>
  <label for="active" class="close"></label>
  <div class="wrapper">
    <ul>

      <li *ngFor="let link of links">
        <a *ngIf="link.external;else internal" [href]="link.path" (click)="href($event)">{{link.name}}</a>
        <ng-template #internal>
          <a (click)="closeModal()" [routerLink]="link.path">{{link.name}}</a>
        </ng-template>
      </li>
    </ul>
  </div>
</nav>

// apps/admin/src/components/Navbar/index.tsx
import React, { MouseEventHandler } from "react";
import './style.css'
import { Link } from "react-router-dom";
export const Navbar = () => {
  const [checked, setChecked] = React.useState(false)
  const toggleMenu = () => {
    setChecked(!checked)
  }
  const handleExternalNavigate:MouseEventHandler<HTMLAnchorElement> = (event) => {
    event.preventDefault()
    setChecked(false)
    const target = event.target as any
    debugger
    setTimeout(() => {
      window.location.href = target.href 
    }, 600);
  }
  return (
    <nav className="navbar--desktop">
      {/* Credits https://codepen.io/yuhomyan/pen/ExKvNVa */}
      <input type="checkbox" id="active" checked={checked} onChange={toggleMenu}/>
      <label htmlFor="active" className="menu-btn">
        <span />
      </label>
      <label htmlFor="active" className="close" />
      <div className="wrapper">
        <ul>
          <li>
            <a onClick={handleExternalNavigate} href="/">About</a>
          </li>
          <li>
            <a onClick={handleExternalNavigate} href="/projects">Projects</a>
          </li>

          <li>
            <a onClick={handleExternalNavigate} href="/contact">Contact</a>
          </li>
          <li>
            <Link to="/">Admin</Link>
          </li>
        </ul>
      </div>
    </nav>
  );
};
