// apps/projects/src/components/Navbar/index.tsx
import React from "react";
import './style.css'
export const Navbar = () => {
  return (
    <nav className="navbar--desktop">
      {/* Credits https://codepen.io/yuhomyan/pen/ExKvNVa */}
      <input type="checkbox" id="active" />
      <label htmlFor="active" className="menu-btn">
        <span />
      </label>
      <label htmlFor="active" className="close" />
      <div className="wrapper">
        <ul>
          <li>
            <a href="/">About</a>
          </li>
          <li>
            <a href="/projects">Projects</a>
          </li>
          <li>
            <a href="/admin">Admin</a>
          </li>
        </ul>
      </div>
    </nav>
  );
};

// apps/projects/src/app/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  isMenuOpen: boolean = false
  links:{path:string,name:string,external:boolean}[] = [


    {
      path:'/',
      name:'About',
      external:true
    },
    {
      path:'/projects',
      name:'Projects',
      external:false
    },
    {
      path:'/contact',
      name:'Contact',
      external:true
    },

    {
      path:'/admin',
      name:'Admin',
      external:true
    }

  ]
  closeModal(){
    console.log('cierrate');
    this.isMenuOpen = false
  }

  setIsOpen(){
    this.isMenuOpen = !this.isMenuOpen
  }
}

<nav class="navbar--desktop">
  <!-- Credits https://codepen.io/yuhomyan/pen/ExKvNVa -->
  <input (click)="setIsOpen()" type="checkbox" [checked]="isMenuOpen" id="active" />
  <label for="active" class="menu-btn"><span></span></label>
  <label for="active" class="close"></label>
  <div class="wrapper">
    <ul>

      <li *ngFor="let link of links">
        <a *ngIf="link.external;else internal" [href]="link.path">{{link.name}}</a>
        <ng-template #internal>
          <a (click)="closeModal()" [routerLink]="link.path">{{link.name}}</a>
        </ng-template>
      </li>
    </ul>
  </div>
</nav>
